Repository tikv/titan, pull requests merged in 2020-06, with the labels that each got.

#161 Fix wrong live data size when encounter rewrite failure
  src/blob_gc_job.cc
  src/db_impl_gc.cc
  src/titan_db_test.cc
Labels: needs-cherry-pick-3.x, needs-cherry-pick-4.x

#164 feat: Titan should return user value to compaction filter #163
  .travis.yml
  CMakeLists.txt
  include/titan/options.h
  src/compaction_filter.h
  src/compaction_filter_test.cc
  src/db_impl.cc
  src/db_impl.h
  src/options.cc
Labels: contribution, needs-cherry-pick-4.x, sig/engine

#172 Fix wrong assert delta < 0 for cocurrent compaction while flush
  .clion.source.upload.marker
  src/blob_format.h
  src/blob_storage.cc
  src/db_impl.cc
  src/db_impl_gc.cc
  src/titan_db_test.cc
Labels: needs-cherry-pick-4.x, status/can-merge

#176 Fix wrong assert delta < 0 for cocurrent compaction while flush (#172)
  .clion.source.upload.marker
  src/blob_format.h
  src/blob_storage.cc
  src/db_impl.cc
  src/db_impl_gc.cc
  src/titan_db_test.cc
Labels: status/can-merge, type/cherry-pick

#169 Fix GC may delete a already deleted blob file (#168)
  src/blob_format.h
  src/blob_gc.cc
  src/blob_gc.h
  src/blob_gc_job.cc
  src/blob_gc_job_test.cc
  src/blob_gc_picker.cc
  src/db_impl_gc.cc
  src/titan_db_test.cc
Labels: status/can-merge, type/cherry-pick
